import './globals.css';

export const metadata = {
  title: 'Coupang Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='font-sans text-xs'>{children}</body>
    </html>
  );
}
